import { writable } from "svelte/store";
import type { CurrentOrganization } from "../../types";

export const mockedOrg: CurrentOrganization = {
  active: false,
  additionalConcurrentWebEvents: 0,
  additionalVodBandwidthGb: 0,
  additionalVodStorageGb: 0,
  additionalWebDataGb: 0,
  allowed16ChannelAudio: false,
  billingYearlyMultiSite: false,
  billingYearlyVod: false,
  billingYearlyWeb: false,
  defaultWebEventProfileType: null,
  managedBy: null,
  msa: false,
  multisitePlanId: "",
  multisitePlanName: "",
  multisiteStartDate: "",
  name: "",
  notes: null,
  numConcurrentTranscodes: 0,
  planName: "",
  regionId: "",
  schedulerVersion: 2,
  subscriptionDetails: { subtitlesHoursPerMonth: 0 },
  usageSummary: {
    enterpriseLicenses: 0,
    lanCloudSiteLicenses: 0,
    nonProductionSiteLicenses: 0,
    professionalLicenses: 0,
    softwareEncoderLicenses: 0,
    webBandwidth: 0,
  },
  uuid: "",
  version: 0,
  vodPlanId: "",
  vodPlanName: "",
  vodStartDate: "",
  webBandwidth: 0,
  webMaxDeleteAfter: 0,
  webPlanId: "",
  webPlanName: "",
  webStartDate: "",
};
export const organization = writable<CurrentOrganization | null>(null);
